-- Platform admins only see projects for their own organisation.
-- Latest user_can_view_project also grants by Strategic Alignment, program,
-- functional area, project, and stream. Same body as
-- supabase/manual/project_access_hierarchy.sql (safe to re-run).
