/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForcePasswordChangeRouteImport } from './routes/force-password-change'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPlatformRouteImport } from './routes/_authenticated/platform'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppAboutRouteImport } from './routes/_authenticated/app.about'
import { Route as AuthenticatedAppActionsRouteImport } from './routes/_authenticated/app.actions'
import { Route as AuthenticatedAppAgileRouteImport } from './routes/_authenticated/app.agile'
import { Route as AuthenticatedAppAiAssistRouteImport } from './routes/_authenticated/app.ai-assist'
import { Route as AuthenticatedAppAuditLogRouteImport } from './routes/_authenticated/app.audit-log'
import { Route as AuthenticatedAppBenefitsRouteImport } from './routes/_authenticated/app.benefits'
import { Route as AuthenticatedAppBillingRouteImport } from './routes/_authenticated/app.billing'
import { Route as AuthenticatedAppBusinessUnitsRouteImport } from './routes/_authenticated/app.business-units'
import { Route as AuthenticatedAppChartThemeRouteImport } from './routes/_authenticated/app.chart-theme'
import { Route as AuthenticatedAppConfigurationRouteImport } from './routes/_authenticated/app.configuration'
import { Route as AuthenticatedAppCostVsBenefitRouteImport } from './routes/_authenticated/app.cost-vs-benefit'
import { Route as AuthenticatedAppDataEditorRouteImport } from './routes/_authenticated/app.data-editor'
import { Route as AuthenticatedAppDecisionsRouteImport } from './routes/_authenticated/app.decisions'
import { Route as AuthenticatedAppDemandPipelineRouteImport } from './routes/_authenticated/app.demand-pipeline'
import { Route as AuthenticatedAppDependenciesRouteImport } from './routes/_authenticated/app.dependencies'
import { Route as AuthenticatedAppExecutiveRouteImport } from './routes/_authenticated/app.executive'
import { Route as AuthenticatedAppExecutiveCockpitRouteImport } from './routes/_authenticated/app.executive-cockpit'
import { Route as AuthenticatedAppExecutiveReportsRouteImport } from './routes/_authenticated/app.executive-reports'
import { Route as AuthenticatedAppFinancialsRouteImport } from './routes/_authenticated/app.financials'
import { Route as AuthenticatedAppFyAllocationRouteImport } from './routes/_authenticated/app.fy-allocation'
import { Route as AuthenticatedAppGovernanceChannelsRouteImport } from './routes/_authenticated/app.governance-channels'
import { Route as AuthenticatedAppIssuesRouteImport } from './routes/_authenticated/app.issues'
import { Route as AuthenticatedAppLatestUpdatesRouteImport } from './routes/_authenticated/app.latest-updates'
import { Route as AuthenticatedAppLessonsRouteImport } from './routes/_authenticated/app.lessons'
import { Route as AuthenticatedAppMyWorkRouteImport } from './routes/_authenticated/app.my-work'
import { Route as AuthenticatedAppNavigationRouteImport } from './routes/_authenticated/app.navigation'
import { Route as AuthenticatedAppPermissionsRouteImport } from './routes/_authenticated/app.permissions'
import { Route as AuthenticatedAppPhaseFinancialsRouteImport } from './routes/_authenticated/app.phase-financials'
import { Route as AuthenticatedAppPortfolioMovementsRouteImport } from './routes/_authenticated/app.portfolio-movements'
import { Route as AuthenticatedAppPortfolioSegmentationRouteImport } from './routes/_authenticated/app.portfolio-segmentation'
import { Route as AuthenticatedAppPrioritisationRouteImport } from './routes/_authenticated/app.prioritisation'
import { Route as AuthenticatedAppProgramsRouteImport } from './routes/_authenticated/app.programs'
import { Route as AuthenticatedAppProjectAccessRouteImport } from './routes/_authenticated/app.project-access'
import { Route as AuthenticatedAppProjectInfographicRouteImport } from './routes/_authenticated/app.project-infographic'
import { Route as AuthenticatedAppProjectPurgeRouteImport } from './routes/_authenticated/app.project-purge'
import { Route as AuthenticatedAppProjectsRouteImport } from './routes/_authenticated/app.projects'
import { Route as AuthenticatedAppReleaseRegisterRouteImport } from './routes/_authenticated/app.release-register'
import { Route as AuthenticatedAppResourcesRouteImport } from './routes/_authenticated/app.resources'
import { Route as AuthenticatedAppRiskRoadmapRouteImport } from './routes/_authenticated/app.risk-roadmap'
import { Route as AuthenticatedAppRisksRouteImport } from './routes/_authenticated/app.risks'
import { Route as AuthenticatedAppRoadmapAnalyticsRouteImport } from './routes/_authenticated/app.roadmap-analytics'
import { Route as AuthenticatedAppRoadmapGovernanceRouteImport } from './routes/_authenticated/app.roadmap-governance'
import { Route as AuthenticatedAppScenariosRouteImport } from './routes/_authenticated/app.scenarios'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppStageGateConfigRouteImport } from './routes/_authenticated/app.stage-gate-config'
import { Route as AuthenticatedAppStageGatesRouteImport } from './routes/_authenticated/app.stage-gates'
import { Route as AuthenticatedAppStakeholdersRouteImport } from './routes/_authenticated/app.stakeholders'
import { Route as AuthenticatedAppTeamRouteImport } from './routes/_authenticated/app.team'
import { Route as AuthenticatedAppTimelineRouteImport } from './routes/_authenticated/app.timeline'
import { Route as AuthenticatedAppWorkItemsRouteImport } from './routes/_authenticated/app.work-items'
import { Route as AuthenticatedPlatformBrandingRouteImport } from './routes/_authenticated/platform.branding'
import { Route as AuthenticatedPlatformExpensesRouteImport } from './routes/_authenticated/platform.expenses'
import { Route as AuthenticatedPlatformFinanceRouteImport } from './routes/_authenticated/platform.finance'
import { Route as AuthenticatedPlatformInvoiceTemplateRouteImport } from './routes/_authenticated/platform.invoice-template'
import { Route as AuthenticatedPlatformInvoicesRouteImport } from './routes/_authenticated/platform.invoices'
import { Route as AuthenticatedPlatformLandingRouteImport } from './routes/_authenticated/platform.landing'
import { Route as AuthenticatedPlatformLimitsRouteImport } from './routes/_authenticated/platform.limits'
import { Route as AuthenticatedPlatformOrganizationsRouteImport } from './routes/_authenticated/platform.organizations'
import { Route as AuthenticatedPlatformPlansRouteImport } from './routes/_authenticated/platform.plans'
import { Route as AuthenticatedPlatformProjectPurgeRouteImport } from './routes/_authenticated/platform.project-purge'
import { Route as AuthenticatedPlatformSettingsRouteImport } from './routes/_authenticated/platform.settings'
import { Route as AuthenticatedPlatformSubscriptionsRouteImport } from './routes/_authenticated/platform.subscriptions'
import { Route as OSlugLoginRouteImport } from './routes/o.$slug.login'
import { Route as AuthenticatedAppInvoiceIdRouteImport } from './routes/_authenticated/app.invoice.$id'
import { Route as AuthenticatedAppProjectsIdRouteImport } from './routes/_authenticated/app.projects.$id'
import { Route as AuthenticatedAppProjectsNewRouteImport } from './routes/_authenticated/app.projects.new'
import { Route as AuthenticatedPlatformInvoiceIdRouteImport } from './routes/_authenticated/platform.invoice.$id'
import { Route as ApiPublicHooksBillingRunRouteImport } from './routes/api/public/hooks/billing-run'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForcePasswordChangeRoute = ForcePasswordChangeRouteImport.update({
  id: '/force-password-change',
  path: '/force-password-change',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlatformRoute = AuthenticatedPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAboutRoute = AuthenticatedAppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppActionsRoute = AuthenticatedAppActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAgileRoute = AuthenticatedAppAgileRouteImport.update({
  id: '/agile',
  path: '/agile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAiAssistRoute =
  AuthenticatedAppAiAssistRouteImport.update({
    id: '/ai-assist',
    path: '/ai-assist',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAuditLogRoute =
  AuthenticatedAppAuditLogRouteImport.update({
    id: '/audit-log',
    path: '/audit-log',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBenefitsRoute =
  AuthenticatedAppBenefitsRouteImport.update({
    id: '/benefits',
    path: '/benefits',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBillingRoute = AuthenticatedAppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBusinessUnitsRoute =
  AuthenticatedAppBusinessUnitsRouteImport.update({
    id: '/business-units',
    path: '/business-units',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppChartThemeRoute =
  AuthenticatedAppChartThemeRouteImport.update({
    id: '/chart-theme',
    path: '/chart-theme',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConfigurationRoute =
  AuthenticatedAppConfigurationRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCostVsBenefitRoute =
  AuthenticatedAppCostVsBenefitRouteImport.update({
    id: '/cost-vs-benefit',
    path: '/cost-vs-benefit',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDataEditorRoute =
  AuthenticatedAppDataEditorRouteImport.update({
    id: '/data-editor',
    path: '/data-editor',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDecisionsRoute =
  AuthenticatedAppDecisionsRouteImport.update({
    id: '/decisions',
    path: '/decisions',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDemandPipelineRoute =
  AuthenticatedAppDemandPipelineRouteImport.update({
    id: '/demand-pipeline',
    path: '/demand-pipeline',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDependenciesRoute =
  AuthenticatedAppDependenciesRouteImport.update({
    id: '/dependencies',
    path: '/dependencies',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppExecutiveRoute =
  AuthenticatedAppExecutiveRouteImport.update({
    id: '/executive',
    path: '/executive',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppExecutiveCockpitRoute =
  AuthenticatedAppExecutiveCockpitRouteImport.update({
    id: '/executive-cockpit',
    path: '/executive-cockpit',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppExecutiveReportsRoute =
  AuthenticatedAppExecutiveReportsRouteImport.update({
    id: '/executive-reports',
    path: '/executive-reports',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFinancialsRoute =
  AuthenticatedAppFinancialsRouteImport.update({
    id: '/financials',
    path: '/financials',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFyAllocationRoute =
  AuthenticatedAppFyAllocationRouteImport.update({
    id: '/fy-allocation',
    path: '/fy-allocation',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppGovernanceChannelsRoute =
  AuthenticatedAppGovernanceChannelsRouteImport.update({
    id: '/governance-channels',
    path: '/governance-channels',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppIssuesRoute = AuthenticatedAppIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppLatestUpdatesRoute =
  AuthenticatedAppLatestUpdatesRouteImport.update({
    id: '/latest-updates',
    path: '/latest-updates',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLessonsRoute = AuthenticatedAppLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMyWorkRoute = AuthenticatedAppMyWorkRouteImport.update({
  id: '/my-work',
  path: '/my-work',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNavigationRoute =
  AuthenticatedAppNavigationRouteImport.update({
    id: '/navigation',
    path: '/navigation',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPermissionsRoute =
  AuthenticatedAppPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPhaseFinancialsRoute =
  AuthenticatedAppPhaseFinancialsRouteImport.update({
    id: '/phase-financials',
    path: '/phase-financials',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPortfolioMovementsRoute =
  AuthenticatedAppPortfolioMovementsRouteImport.update({
    id: '/portfolio-movements',
    path: '/portfolio-movements',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPortfolioSegmentationRoute =
  AuthenticatedAppPortfolioSegmentationRouteImport.update({
    id: '/portfolio-segmentation',
    path: '/portfolio-segmentation',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPrioritisationRoute =
  AuthenticatedAppPrioritisationRouteImport.update({
    id: '/prioritisation',
    path: '/prioritisation',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProgramsRoute =
  AuthenticatedAppProgramsRouteImport.update({
    id: '/programs',
    path: '/programs',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProjectAccessRoute =
  AuthenticatedAppProjectAccessRouteImport.update({
    id: '/project-access',
    path: '/project-access',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProjectInfographicRoute =
  AuthenticatedAppProjectInfographicRouteImport.update({
    id: '/project-infographic',
    path: '/project-infographic',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProjectPurgeRoute =
  AuthenticatedAppProjectPurgeRouteImport.update({
    id: '/project-purge',
    path: '/project-purge',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProjectsRoute =
  AuthenticatedAppProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppReleaseRegisterRoute =
  AuthenticatedAppReleaseRegisterRouteImport.update({
    id: '/release-register',
    path: '/release-register',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppResourcesRoute =
  AuthenticatedAppResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRiskRoadmapRoute =
  AuthenticatedAppRiskRoadmapRouteImport.update({
    id: '/risk-roadmap',
    path: '/risk-roadmap',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRisksRoute = AuthenticatedAppRisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRoadmapAnalyticsRoute =
  AuthenticatedAppRoadmapAnalyticsRouteImport.update({
    id: '/roadmap-analytics',
    path: '/roadmap-analytics',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRoadmapGovernanceRoute =
  AuthenticatedAppRoadmapGovernanceRouteImport.update({
    id: '/roadmap-governance',
    path: '/roadmap-governance',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppScenariosRoute =
  AuthenticatedAppScenariosRouteImport.update({
    id: '/scenarios',
    path: '/scenarios',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppStageGateConfigRoute =
  AuthenticatedAppStageGateConfigRouteImport.update({
    id: '/stage-gate-config',
    path: '/stage-gate-config',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppStageGatesRoute =
  AuthenticatedAppStageGatesRouteImport.update({
    id: '/stage-gates',
    path: '/stage-gates',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppStakeholdersRoute =
  AuthenticatedAppStakeholdersRouteImport.update({
    id: '/stakeholders',
    path: '/stakeholders',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTeamRoute = AuthenticatedAppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTimelineRoute =
  AuthenticatedAppTimelineRouteImport.update({
    id: '/timeline',
    path: '/timeline',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppWorkItemsRoute =
  AuthenticatedAppWorkItemsRouteImport.update({
    id: '/work-items',
    path: '/work-items',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedPlatformBrandingRoute =
  AuthenticatedPlatformBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformExpensesRoute =
  AuthenticatedPlatformExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformFinanceRoute =
  AuthenticatedPlatformFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformInvoiceTemplateRoute =
  AuthenticatedPlatformInvoiceTemplateRouteImport.update({
    id: '/invoice-template',
    path: '/invoice-template',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformInvoicesRoute =
  AuthenticatedPlatformInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformLandingRoute =
  AuthenticatedPlatformLandingRouteImport.update({
    id: '/landing',
    path: '/landing',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformLimitsRoute =
  AuthenticatedPlatformLimitsRouteImport.update({
    id: '/limits',
    path: '/limits',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformOrganizationsRoute =
  AuthenticatedPlatformOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformPlansRoute =
  AuthenticatedPlatformPlansRouteImport.update({
    id: '/plans',
    path: '/plans',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformProjectPurgeRoute =
  AuthenticatedPlatformProjectPurgeRouteImport.update({
    id: '/project-purge',
    path: '/project-purge',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformSettingsRoute =
  AuthenticatedPlatformSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformSubscriptionsRoute =
  AuthenticatedPlatformSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const OSlugLoginRoute = OSlugLoginRouteImport.update({
  id: '/o/$slug/login',
  path: '/o/$slug/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppInvoiceIdRoute =
  AuthenticatedAppInvoiceIdRouteImport.update({
    id: '/invoice/$id',
    path: '/invoice/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProjectsIdRoute =
  AuthenticatedAppProjectsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppProjectsRoute,
  } as any)
const AuthenticatedAppProjectsNewRoute =
  AuthenticatedAppProjectsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAppProjectsRoute,
  } as any)
const AuthenticatedPlatformInvoiceIdRoute =
  AuthenticatedPlatformInvoiceIdRouteImport.update({
    id: '/invoice/$id',
    path: '/invoice/$id',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const ApiPublicHooksBillingRunRoute =
  ApiPublicHooksBillingRunRouteImport.update({
    id: '/api/public/hooks/billing-run',
    path: '/api/public/hooks/billing-run',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/force-password-change': typeof ForcePasswordChangeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/platform': typeof AuthenticatedPlatformRouteWithChildren
  '/app/about': typeof AuthenticatedAppAboutRoute
  '/app/actions': typeof AuthenticatedAppActionsRoute
  '/app/agile': typeof AuthenticatedAppAgileRoute
  '/app/ai-assist': typeof AuthenticatedAppAiAssistRoute
  '/app/audit-log': typeof AuthenticatedAppAuditLogRoute
  '/app/benefits': typeof AuthenticatedAppBenefitsRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/business-units': typeof AuthenticatedAppBusinessUnitsRoute
  '/app/chart-theme': typeof AuthenticatedAppChartThemeRoute
  '/app/configuration': typeof AuthenticatedAppConfigurationRoute
  '/app/cost-vs-benefit': typeof AuthenticatedAppCostVsBenefitRoute
  '/app/data-editor': typeof AuthenticatedAppDataEditorRoute
  '/app/decisions': typeof AuthenticatedAppDecisionsRoute
  '/app/demand-pipeline': typeof AuthenticatedAppDemandPipelineRoute
  '/app/dependencies': typeof AuthenticatedAppDependenciesRoute
  '/app/executive': typeof AuthenticatedAppExecutiveRoute
  '/app/executive-cockpit': typeof AuthenticatedAppExecutiveCockpitRoute
  '/app/executive-reports': typeof AuthenticatedAppExecutiveReportsRoute
  '/app/financials': typeof AuthenticatedAppFinancialsRoute
  '/app/fy-allocation': typeof AuthenticatedAppFyAllocationRoute
  '/app/governance-channels': typeof AuthenticatedAppGovernanceChannelsRoute
  '/app/issues': typeof AuthenticatedAppIssuesRoute
  '/app/latest-updates': typeof AuthenticatedAppLatestUpdatesRoute
  '/app/lessons': typeof AuthenticatedAppLessonsRoute
  '/app/my-work': typeof AuthenticatedAppMyWorkRoute
  '/app/navigation': typeof AuthenticatedAppNavigationRoute
  '/app/permissions': typeof AuthenticatedAppPermissionsRoute
  '/app/phase-financials': typeof AuthenticatedAppPhaseFinancialsRoute
  '/app/portfolio-movements': typeof AuthenticatedAppPortfolioMovementsRoute
  '/app/portfolio-segmentation': typeof AuthenticatedAppPortfolioSegmentationRoute
  '/app/prioritisation': typeof AuthenticatedAppPrioritisationRoute
  '/app/programs': typeof AuthenticatedAppProgramsRoute
  '/app/project-access': typeof AuthenticatedAppProjectAccessRoute
  '/app/project-infographic': typeof AuthenticatedAppProjectInfographicRoute
  '/app/project-purge': typeof AuthenticatedAppProjectPurgeRoute
  '/app/projects': typeof AuthenticatedAppProjectsRouteWithChildren
  '/app/release-register': typeof AuthenticatedAppReleaseRegisterRoute
  '/app/resources': typeof AuthenticatedAppResourcesRoute
  '/app/risk-roadmap': typeof AuthenticatedAppRiskRoadmapRoute
  '/app/risks': typeof AuthenticatedAppRisksRoute
  '/app/roadmap-analytics': typeof AuthenticatedAppRoadmapAnalyticsRoute
  '/app/roadmap-governance': typeof AuthenticatedAppRoadmapGovernanceRoute
  '/app/scenarios': typeof AuthenticatedAppScenariosRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/stage-gate-config': typeof AuthenticatedAppStageGateConfigRoute
  '/app/stage-gates': typeof AuthenticatedAppStageGatesRoute
  '/app/stakeholders': typeof AuthenticatedAppStakeholdersRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/app/timeline': typeof AuthenticatedAppTimelineRoute
  '/app/work-items': typeof AuthenticatedAppWorkItemsRoute
  '/platform/branding': typeof AuthenticatedPlatformBrandingRoute
  '/platform/expenses': typeof AuthenticatedPlatformExpensesRoute
  '/platform/finance': typeof AuthenticatedPlatformFinanceRoute
  '/platform/invoice-template': typeof AuthenticatedPlatformInvoiceTemplateRoute
  '/platform/invoices': typeof AuthenticatedPlatformInvoicesRoute
  '/platform/landing': typeof AuthenticatedPlatformLandingRoute
  '/platform/limits': typeof AuthenticatedPlatformLimitsRoute
  '/platform/organizations': typeof AuthenticatedPlatformOrganizationsRoute
  '/platform/plans': typeof AuthenticatedPlatformPlansRoute
  '/platform/project-purge': typeof AuthenticatedPlatformProjectPurgeRoute
  '/platform/settings': typeof AuthenticatedPlatformSettingsRoute
  '/platform/subscriptions': typeof AuthenticatedPlatformSubscriptionsRoute
  '/o/$slug/login': typeof OSlugLoginRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/invoice/$id': typeof AuthenticatedAppInvoiceIdRoute
  '/app/projects/$id': typeof AuthenticatedAppProjectsIdRoute
  '/app/projects/new': typeof AuthenticatedAppProjectsNewRoute
  '/platform/invoice/$id': typeof AuthenticatedPlatformInvoiceIdRoute
  '/api/public/hooks/billing-run': typeof ApiPublicHooksBillingRunRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/force-password-change': typeof ForcePasswordChangeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/platform': typeof AuthenticatedPlatformRouteWithChildren
  '/app/about': typeof AuthenticatedAppAboutRoute
  '/app/actions': typeof AuthenticatedAppActionsRoute
  '/app/agile': typeof AuthenticatedAppAgileRoute
  '/app/ai-assist': typeof AuthenticatedAppAiAssistRoute
  '/app/audit-log': typeof AuthenticatedAppAuditLogRoute
  '/app/benefits': typeof AuthenticatedAppBenefitsRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/business-units': typeof AuthenticatedAppBusinessUnitsRoute
  '/app/chart-theme': typeof AuthenticatedAppChartThemeRoute
  '/app/configuration': typeof AuthenticatedAppConfigurationRoute
  '/app/cost-vs-benefit': typeof AuthenticatedAppCostVsBenefitRoute
  '/app/data-editor': typeof AuthenticatedAppDataEditorRoute
  '/app/decisions': typeof AuthenticatedAppDecisionsRoute
  '/app/demand-pipeline': typeof AuthenticatedAppDemandPipelineRoute
  '/app/dependencies': typeof AuthenticatedAppDependenciesRoute
  '/app/executive': typeof AuthenticatedAppExecutiveRoute
  '/app/executive-cockpit': typeof AuthenticatedAppExecutiveCockpitRoute
  '/app/executive-reports': typeof AuthenticatedAppExecutiveReportsRoute
  '/app/financials': typeof AuthenticatedAppFinancialsRoute
  '/app/fy-allocation': typeof AuthenticatedAppFyAllocationRoute
  '/app/governance-channels': typeof AuthenticatedAppGovernanceChannelsRoute
  '/app/issues': typeof AuthenticatedAppIssuesRoute
  '/app/latest-updates': typeof AuthenticatedAppLatestUpdatesRoute
  '/app/lessons': typeof AuthenticatedAppLessonsRoute
  '/app/my-work': typeof AuthenticatedAppMyWorkRoute
  '/app/navigation': typeof AuthenticatedAppNavigationRoute
  '/app/permissions': typeof AuthenticatedAppPermissionsRoute
  '/app/phase-financials': typeof AuthenticatedAppPhaseFinancialsRoute
  '/app/portfolio-movements': typeof AuthenticatedAppPortfolioMovementsRoute
  '/app/portfolio-segmentation': typeof AuthenticatedAppPortfolioSegmentationRoute
  '/app/prioritisation': typeof AuthenticatedAppPrioritisationRoute
  '/app/programs': typeof AuthenticatedAppProgramsRoute
  '/app/project-access': typeof AuthenticatedAppProjectAccessRoute
  '/app/project-infographic': typeof AuthenticatedAppProjectInfographicRoute
  '/app/project-purge': typeof AuthenticatedAppProjectPurgeRoute
  '/app/projects': typeof AuthenticatedAppProjectsRouteWithChildren
  '/app/release-register': typeof AuthenticatedAppReleaseRegisterRoute
  '/app/resources': typeof AuthenticatedAppResourcesRoute
  '/app/risk-roadmap': typeof AuthenticatedAppRiskRoadmapRoute
  '/app/risks': typeof AuthenticatedAppRisksRoute
  '/app/roadmap-analytics': typeof AuthenticatedAppRoadmapAnalyticsRoute
  '/app/roadmap-governance': typeof AuthenticatedAppRoadmapGovernanceRoute
  '/app/scenarios': typeof AuthenticatedAppScenariosRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/stage-gate-config': typeof AuthenticatedAppStageGateConfigRoute
  '/app/stage-gates': typeof AuthenticatedAppStageGatesRoute
  '/app/stakeholders': typeof AuthenticatedAppStakeholdersRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/app/timeline': typeof AuthenticatedAppTimelineRoute
  '/app/work-items': typeof AuthenticatedAppWorkItemsRoute
  '/platform/branding': typeof AuthenticatedPlatformBrandingRoute
  '/platform/expenses': typeof AuthenticatedPlatformExpensesRoute
  '/platform/finance': typeof AuthenticatedPlatformFinanceRoute
  '/platform/invoice-template': typeof AuthenticatedPlatformInvoiceTemplateRoute
  '/platform/invoices': typeof AuthenticatedPlatformInvoicesRoute
  '/platform/landing': typeof AuthenticatedPlatformLandingRoute
  '/platform/limits': typeof AuthenticatedPlatformLimitsRoute
  '/platform/organizations': typeof AuthenticatedPlatformOrganizationsRoute
  '/platform/plans': typeof AuthenticatedPlatformPlansRoute
  '/platform/project-purge': typeof AuthenticatedPlatformProjectPurgeRoute
  '/platform/settings': typeof AuthenticatedPlatformSettingsRoute
  '/platform/subscriptions': typeof AuthenticatedPlatformSubscriptionsRoute
  '/o/$slug/login': typeof OSlugLoginRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/invoice/$id': typeof AuthenticatedAppInvoiceIdRoute
  '/app/projects/$id': typeof AuthenticatedAppProjectsIdRoute
  '/app/projects/new': typeof AuthenticatedAppProjectsNewRoute
  '/platform/invoice/$id': typeof AuthenticatedPlatformInvoiceIdRoute
  '/api/public/hooks/billing-run': typeof ApiPublicHooksBillingRunRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/force-password-change': typeof ForcePasswordChangeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/platform': typeof AuthenticatedPlatformRouteWithChildren
  '/_authenticated/app/about': typeof AuthenticatedAppAboutRoute
  '/_authenticated/app/actions': typeof AuthenticatedAppActionsRoute
  '/_authenticated/app/agile': typeof AuthenticatedAppAgileRoute
  '/_authenticated/app/ai-assist': typeof AuthenticatedAppAiAssistRoute
  '/_authenticated/app/audit-log': typeof AuthenticatedAppAuditLogRoute
  '/_authenticated/app/benefits': typeof AuthenticatedAppBenefitsRoute
  '/_authenticated/app/billing': typeof AuthenticatedAppBillingRoute
  '/_authenticated/app/business-units': typeof AuthenticatedAppBusinessUnitsRoute
  '/_authenticated/app/chart-theme': typeof AuthenticatedAppChartThemeRoute
  '/_authenticated/app/configuration': typeof AuthenticatedAppConfigurationRoute
  '/_authenticated/app/cost-vs-benefit': typeof AuthenticatedAppCostVsBenefitRoute
  '/_authenticated/app/data-editor': typeof AuthenticatedAppDataEditorRoute
  '/_authenticated/app/decisions': typeof AuthenticatedAppDecisionsRoute
  '/_authenticated/app/demand-pipeline': typeof AuthenticatedAppDemandPipelineRoute
  '/_authenticated/app/dependencies': typeof AuthenticatedAppDependenciesRoute
  '/_authenticated/app/executive': typeof AuthenticatedAppExecutiveRoute
  '/_authenticated/app/executive-cockpit': typeof AuthenticatedAppExecutiveCockpitRoute
  '/_authenticated/app/executive-reports': typeof AuthenticatedAppExecutiveReportsRoute
  '/_authenticated/app/financials': typeof AuthenticatedAppFinancialsRoute
  '/_authenticated/app/fy-allocation': typeof AuthenticatedAppFyAllocationRoute
  '/_authenticated/app/governance-channels': typeof AuthenticatedAppGovernanceChannelsRoute
  '/_authenticated/app/issues': typeof AuthenticatedAppIssuesRoute
  '/_authenticated/app/latest-updates': typeof AuthenticatedAppLatestUpdatesRoute
  '/_authenticated/app/lessons': typeof AuthenticatedAppLessonsRoute
  '/_authenticated/app/my-work': typeof AuthenticatedAppMyWorkRoute
  '/_authenticated/app/navigation': typeof AuthenticatedAppNavigationRoute
  '/_authenticated/app/permissions': typeof AuthenticatedAppPermissionsRoute
  '/_authenticated/app/phase-financials': typeof AuthenticatedAppPhaseFinancialsRoute
  '/_authenticated/app/portfolio-movements': typeof AuthenticatedAppPortfolioMovementsRoute
  '/_authenticated/app/portfolio-segmentation': typeof AuthenticatedAppPortfolioSegmentationRoute
  '/_authenticated/app/prioritisation': typeof AuthenticatedAppPrioritisationRoute
  '/_authenticated/app/programs': typeof AuthenticatedAppProgramsRoute
  '/_authenticated/app/project-access': typeof AuthenticatedAppProjectAccessRoute
  '/_authenticated/app/project-infographic': typeof AuthenticatedAppProjectInfographicRoute
  '/_authenticated/app/project-purge': typeof AuthenticatedAppProjectPurgeRoute
  '/_authenticated/app/projects': typeof AuthenticatedAppProjectsRouteWithChildren
  '/_authenticated/app/release-register': typeof AuthenticatedAppReleaseRegisterRoute
  '/_authenticated/app/resources': typeof AuthenticatedAppResourcesRoute
  '/_authenticated/app/risk-roadmap': typeof AuthenticatedAppRiskRoadmapRoute
  '/_authenticated/app/risks': typeof AuthenticatedAppRisksRoute
  '/_authenticated/app/roadmap-analytics': typeof AuthenticatedAppRoadmapAnalyticsRoute
  '/_authenticated/app/roadmap-governance': typeof AuthenticatedAppRoadmapGovernanceRoute
  '/_authenticated/app/scenarios': typeof AuthenticatedAppScenariosRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/stage-gate-config': typeof AuthenticatedAppStageGateConfigRoute
  '/_authenticated/app/stage-gates': typeof AuthenticatedAppStageGatesRoute
  '/_authenticated/app/stakeholders': typeof AuthenticatedAppStakeholdersRoute
  '/_authenticated/app/team': typeof AuthenticatedAppTeamRoute
  '/_authenticated/app/timeline': typeof AuthenticatedAppTimelineRoute
  '/_authenticated/app/work-items': typeof AuthenticatedAppWorkItemsRoute
  '/_authenticated/platform/branding': typeof AuthenticatedPlatformBrandingRoute
  '/_authenticated/platform/expenses': typeof AuthenticatedPlatformExpensesRoute
  '/_authenticated/platform/finance': typeof AuthenticatedPlatformFinanceRoute
  '/_authenticated/platform/invoice-template': typeof AuthenticatedPlatformInvoiceTemplateRoute
  '/_authenticated/platform/invoices': typeof AuthenticatedPlatformInvoicesRoute
  '/_authenticated/platform/landing': typeof AuthenticatedPlatformLandingRoute
  '/_authenticated/platform/limits': typeof AuthenticatedPlatformLimitsRoute
  '/_authenticated/platform/organizations': typeof AuthenticatedPlatformOrganizationsRoute
  '/_authenticated/platform/plans': typeof AuthenticatedPlatformPlansRoute
  '/_authenticated/platform/project-purge': typeof AuthenticatedPlatformProjectPurgeRoute
  '/_authenticated/platform/settings': typeof AuthenticatedPlatformSettingsRoute
  '/_authenticated/platform/subscriptions': typeof AuthenticatedPlatformSubscriptionsRoute
  '/o/$slug/login': typeof OSlugLoginRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/invoice/$id': typeof AuthenticatedAppInvoiceIdRoute
  '/_authenticated/app/projects/$id': typeof AuthenticatedAppProjectsIdRoute
  '/_authenticated/app/projects/new': typeof AuthenticatedAppProjectsNewRoute
  '/_authenticated/platform/invoice/$id': typeof AuthenticatedPlatformInvoiceIdRoute
  '/api/public/hooks/billing-run': typeof ApiPublicHooksBillingRunRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/force-password-change'
    | '/reset-password'
    | '/app'
    | '/onboarding'
    | '/platform'
    | '/app/about'
    | '/app/actions'
    | '/app/agile'
    | '/app/ai-assist'
    | '/app/audit-log'
    | '/app/benefits'
    | '/app/billing'
    | '/app/business-units'
    | '/app/chart-theme'
    | '/app/configuration'
    | '/app/cost-vs-benefit'
    | '/app/data-editor'
    | '/app/decisions'
    | '/app/demand-pipeline'
    | '/app/dependencies'
    | '/app/executive'
    | '/app/executive-cockpit'
    | '/app/executive-reports'
    | '/app/financials'
    | '/app/fy-allocation'
    | '/app/governance-channels'
    | '/app/issues'
    | '/app/latest-updates'
    | '/app/lessons'
    | '/app/my-work'
    | '/app/navigation'
    | '/app/permissions'
    | '/app/phase-financials'
    | '/app/portfolio-movements'
    | '/app/portfolio-segmentation'
    | '/app/prioritisation'
    | '/app/programs'
    | '/app/project-access'
    | '/app/project-infographic'
    | '/app/project-purge'
    | '/app/projects'
    | '/app/release-register'
    | '/app/resources'
    | '/app/risk-roadmap'
    | '/app/risks'
    | '/app/roadmap-analytics'
    | '/app/roadmap-governance'
    | '/app/scenarios'
    | '/app/settings'
    | '/app/stage-gate-config'
    | '/app/stage-gates'
    | '/app/stakeholders'
    | '/app/team'
    | '/app/timeline'
    | '/app/work-items'
    | '/platform/branding'
    | '/platform/expenses'
    | '/platform/finance'
    | '/platform/invoice-template'
    | '/platform/invoices'
    | '/platform/landing'
    | '/platform/limits'
    | '/platform/organizations'
    | '/platform/plans'
    | '/platform/project-purge'
    | '/platform/settings'
    | '/platform/subscriptions'
    | '/o/$slug/login'
    | '/app/'
    | '/app/invoice/$id'
    | '/app/projects/$id'
    | '/app/projects/new'
    | '/platform/invoice/$id'
    | '/api/public/hooks/billing-run'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/force-password-change'
    | '/reset-password'
    | '/onboarding'
    | '/platform'
    | '/app/about'
    | '/app/actions'
    | '/app/agile'
    | '/app/ai-assist'
    | '/app/audit-log'
    | '/app/benefits'
    | '/app/billing'
    | '/app/business-units'
    | '/app/chart-theme'
    | '/app/configuration'
    | '/app/cost-vs-benefit'
    | '/app/data-editor'
    | '/app/decisions'
    | '/app/demand-pipeline'
    | '/app/dependencies'
    | '/app/executive'
    | '/app/executive-cockpit'
    | '/app/executive-reports'
    | '/app/financials'
    | '/app/fy-allocation'
    | '/app/governance-channels'
    | '/app/issues'
    | '/app/latest-updates'
    | '/app/lessons'
    | '/app/my-work'
    | '/app/navigation'
    | '/app/permissions'
    | '/app/phase-financials'
    | '/app/portfolio-movements'
    | '/app/portfolio-segmentation'
    | '/app/prioritisation'
    | '/app/programs'
    | '/app/project-access'
    | '/app/project-infographic'
    | '/app/project-purge'
    | '/app/projects'
    | '/app/release-register'
    | '/app/resources'
    | '/app/risk-roadmap'
    | '/app/risks'
    | '/app/roadmap-analytics'
    | '/app/roadmap-governance'
    | '/app/scenarios'
    | '/app/settings'
    | '/app/stage-gate-config'
    | '/app/stage-gates'
    | '/app/stakeholders'
    | '/app/team'
    | '/app/timeline'
    | '/app/work-items'
    | '/platform/branding'
    | '/platform/expenses'
    | '/platform/finance'
    | '/platform/invoice-template'
    | '/platform/invoices'
    | '/platform/landing'
    | '/platform/limits'
    | '/platform/organizations'
    | '/platform/plans'
    | '/platform/project-purge'
    | '/platform/settings'
    | '/platform/subscriptions'
    | '/o/$slug/login'
    | '/app'
    | '/app/invoice/$id'
    | '/app/projects/$id'
    | '/app/projects/new'
    | '/platform/invoice/$id'
    | '/api/public/hooks/billing-run'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/force-password-change'
    | '/reset-password'
    | '/_authenticated/app'
    | '/_authenticated/onboarding'
    | '/_authenticated/platform'
    | '/_authenticated/app/about'
    | '/_authenticated/app/actions'
    | '/_authenticated/app/agile'
    | '/_authenticated/app/ai-assist'
    | '/_authenticated/app/audit-log'
    | '/_authenticated/app/benefits'
    | '/_authenticated/app/billing'
    | '/_authenticated/app/business-units'
    | '/_authenticated/app/chart-theme'
    | '/_authenticated/app/configuration'
    | '/_authenticated/app/cost-vs-benefit'
    | '/_authenticated/app/data-editor'
    | '/_authenticated/app/decisions'
    | '/_authenticated/app/demand-pipeline'
    | '/_authenticated/app/dependencies'
    | '/_authenticated/app/executive'
    | '/_authenticated/app/executive-cockpit'
    | '/_authenticated/app/executive-reports'
    | '/_authenticated/app/financials'
    | '/_authenticated/app/fy-allocation'
    | '/_authenticated/app/governance-channels'
    | '/_authenticated/app/issues'
    | '/_authenticated/app/latest-updates'
    | '/_authenticated/app/lessons'
    | '/_authenticated/app/my-work'
    | '/_authenticated/app/navigation'
    | '/_authenticated/app/permissions'
    | '/_authenticated/app/phase-financials'
    | '/_authenticated/app/portfolio-movements'
    | '/_authenticated/app/portfolio-segmentation'
    | '/_authenticated/app/prioritisation'
    | '/_authenticated/app/programs'
    | '/_authenticated/app/project-access'
    | '/_authenticated/app/project-infographic'
    | '/_authenticated/app/project-purge'
    | '/_authenticated/app/projects'
    | '/_authenticated/app/release-register'
    | '/_authenticated/app/resources'
    | '/_authenticated/app/risk-roadmap'
    | '/_authenticated/app/risks'
    | '/_authenticated/app/roadmap-analytics'
    | '/_authenticated/app/roadmap-governance'
    | '/_authenticated/app/scenarios'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/stage-gate-config'
    | '/_authenticated/app/stage-gates'
    | '/_authenticated/app/stakeholders'
    | '/_authenticated/app/team'
    | '/_authenticated/app/timeline'
    | '/_authenticated/app/work-items'
    | '/_authenticated/platform/branding'
    | '/_authenticated/platform/expenses'
    | '/_authenticated/platform/finance'
    | '/_authenticated/platform/invoice-template'
    | '/_authenticated/platform/invoices'
    | '/_authenticated/platform/landing'
    | '/_authenticated/platform/limits'
    | '/_authenticated/platform/organizations'
    | '/_authenticated/platform/plans'
    | '/_authenticated/platform/project-purge'
    | '/_authenticated/platform/settings'
    | '/_authenticated/platform/subscriptions'
    | '/o/$slug/login'
    | '/_authenticated/app/'
    | '/_authenticated/app/invoice/$id'
    | '/_authenticated/app/projects/$id'
    | '/_authenticated/app/projects/new'
    | '/_authenticated/platform/invoice/$id'
    | '/api/public/hooks/billing-run'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForcePasswordChangeRoute: typeof ForcePasswordChangeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  OSlugLoginRoute: typeof OSlugLoginRoute
  ApiPublicHooksBillingRunRoute: typeof ApiPublicHooksBillingRunRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/force-password-change': {
      id: '/force-password-change'
      path: '/force-password-change'
      fullPath: '/force-password-change'
      preLoaderRoute: typeof ForcePasswordChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform': {
      id: '/_authenticated/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof AuthenticatedPlatformRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/about': {
      id: '/_authenticated/app/about'
      path: '/about'
      fullPath: '/app/about'
      preLoaderRoute: typeof AuthenticatedAppAboutRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/actions': {
      id: '/_authenticated/app/actions'
      path: '/actions'
      fullPath: '/app/actions'
      preLoaderRoute: typeof AuthenticatedAppActionsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/agile': {
      id: '/_authenticated/app/agile'
      path: '/agile'
      fullPath: '/app/agile'
      preLoaderRoute: typeof AuthenticatedAppAgileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ai-assist': {
      id: '/_authenticated/app/ai-assist'
      path: '/ai-assist'
      fullPath: '/app/ai-assist'
      preLoaderRoute: typeof AuthenticatedAppAiAssistRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/audit-log': {
      id: '/_authenticated/app/audit-log'
      path: '/audit-log'
      fullPath: '/app/audit-log'
      preLoaderRoute: typeof AuthenticatedAppAuditLogRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/benefits': {
      id: '/_authenticated/app/benefits'
      path: '/benefits'
      fullPath: '/app/benefits'
      preLoaderRoute: typeof AuthenticatedAppBenefitsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/billing': {
      id: '/_authenticated/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AuthenticatedAppBillingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/business-units': {
      id: '/_authenticated/app/business-units'
      path: '/business-units'
      fullPath: '/app/business-units'
      preLoaderRoute: typeof AuthenticatedAppBusinessUnitsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/chart-theme': {
      id: '/_authenticated/app/chart-theme'
      path: '/chart-theme'
      fullPath: '/app/chart-theme'
      preLoaderRoute: typeof AuthenticatedAppChartThemeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/configuration': {
      id: '/_authenticated/app/configuration'
      path: '/configuration'
      fullPath: '/app/configuration'
      preLoaderRoute: typeof AuthenticatedAppConfigurationRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/cost-vs-benefit': {
      id: '/_authenticated/app/cost-vs-benefit'
      path: '/cost-vs-benefit'
      fullPath: '/app/cost-vs-benefit'
      preLoaderRoute: typeof AuthenticatedAppCostVsBenefitRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/data-editor': {
      id: '/_authenticated/app/data-editor'
      path: '/data-editor'
      fullPath: '/app/data-editor'
      preLoaderRoute: typeof AuthenticatedAppDataEditorRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/decisions': {
      id: '/_authenticated/app/decisions'
      path: '/decisions'
      fullPath: '/app/decisions'
      preLoaderRoute: typeof AuthenticatedAppDecisionsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/demand-pipeline': {
      id: '/_authenticated/app/demand-pipeline'
      path: '/demand-pipeline'
      fullPath: '/app/demand-pipeline'
      preLoaderRoute: typeof AuthenticatedAppDemandPipelineRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/dependencies': {
      id: '/_authenticated/app/dependencies'
      path: '/dependencies'
      fullPath: '/app/dependencies'
      preLoaderRoute: typeof AuthenticatedAppDependenciesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/executive': {
      id: '/_authenticated/app/executive'
      path: '/executive'
      fullPath: '/app/executive'
      preLoaderRoute: typeof AuthenticatedAppExecutiveRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/executive-cockpit': {
      id: '/_authenticated/app/executive-cockpit'
      path: '/executive-cockpit'
      fullPath: '/app/executive-cockpit'
      preLoaderRoute: typeof AuthenticatedAppExecutiveCockpitRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/executive-reports': {
      id: '/_authenticated/app/executive-reports'
      path: '/executive-reports'
      fullPath: '/app/executive-reports'
      preLoaderRoute: typeof AuthenticatedAppExecutiveReportsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/financials': {
      id: '/_authenticated/app/financials'
      path: '/financials'
      fullPath: '/app/financials'
      preLoaderRoute: typeof AuthenticatedAppFinancialsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/fy-allocation': {
      id: '/_authenticated/app/fy-allocation'
      path: '/fy-allocation'
      fullPath: '/app/fy-allocation'
      preLoaderRoute: typeof AuthenticatedAppFyAllocationRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/governance-channels': {
      id: '/_authenticated/app/governance-channels'
      path: '/governance-channels'
      fullPath: '/app/governance-channels'
      preLoaderRoute: typeof AuthenticatedAppGovernanceChannelsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/issues': {
      id: '/_authenticated/app/issues'
      path: '/issues'
      fullPath: '/app/issues'
      preLoaderRoute: typeof AuthenticatedAppIssuesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/latest-updates': {
      id: '/_authenticated/app/latest-updates'
      path: '/latest-updates'
      fullPath: '/app/latest-updates'
      preLoaderRoute: typeof AuthenticatedAppLatestUpdatesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/lessons': {
      id: '/_authenticated/app/lessons'
      path: '/lessons'
      fullPath: '/app/lessons'
      preLoaderRoute: typeof AuthenticatedAppLessonsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/my-work': {
      id: '/_authenticated/app/my-work'
      path: '/my-work'
      fullPath: '/app/my-work'
      preLoaderRoute: typeof AuthenticatedAppMyWorkRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/navigation': {
      id: '/_authenticated/app/navigation'
      path: '/navigation'
      fullPath: '/app/navigation'
      preLoaderRoute: typeof AuthenticatedAppNavigationRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/permissions': {
      id: '/_authenticated/app/permissions'
      path: '/permissions'
      fullPath: '/app/permissions'
      preLoaderRoute: typeof AuthenticatedAppPermissionsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/phase-financials': {
      id: '/_authenticated/app/phase-financials'
      path: '/phase-financials'
      fullPath: '/app/phase-financials'
      preLoaderRoute: typeof AuthenticatedAppPhaseFinancialsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/portfolio-movements': {
      id: '/_authenticated/app/portfolio-movements'
      path: '/portfolio-movements'
      fullPath: '/app/portfolio-movements'
      preLoaderRoute: typeof AuthenticatedAppPortfolioMovementsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/portfolio-segmentation': {
      id: '/_authenticated/app/portfolio-segmentation'
      path: '/portfolio-segmentation'
      fullPath: '/app/portfolio-segmentation'
      preLoaderRoute: typeof AuthenticatedAppPortfolioSegmentationRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/prioritisation': {
      id: '/_authenticated/app/prioritisation'
      path: '/prioritisation'
      fullPath: '/app/prioritisation'
      preLoaderRoute: typeof AuthenticatedAppPrioritisationRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/programs': {
      id: '/_authenticated/app/programs'
      path: '/programs'
      fullPath: '/app/programs'
      preLoaderRoute: typeof AuthenticatedAppProgramsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/project-access': {
      id: '/_authenticated/app/project-access'
      path: '/project-access'
      fullPath: '/app/project-access'
      preLoaderRoute: typeof AuthenticatedAppProjectAccessRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/project-infographic': {
      id: '/_authenticated/app/project-infographic'
      path: '/project-infographic'
      fullPath: '/app/project-infographic'
      preLoaderRoute: typeof AuthenticatedAppProjectInfographicRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/project-purge': {
      id: '/_authenticated/app/project-purge'
      path: '/project-purge'
      fullPath: '/app/project-purge'
      preLoaderRoute: typeof AuthenticatedAppProjectPurgeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/projects': {
      id: '/_authenticated/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AuthenticatedAppProjectsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/release-register': {
      id: '/_authenticated/app/release-register'
      path: '/release-register'
      fullPath: '/app/release-register'
      preLoaderRoute: typeof AuthenticatedAppReleaseRegisterRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/resources': {
      id: '/_authenticated/app/resources'
      path: '/resources'
      fullPath: '/app/resources'
      preLoaderRoute: typeof AuthenticatedAppResourcesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/risk-roadmap': {
      id: '/_authenticated/app/risk-roadmap'
      path: '/risk-roadmap'
      fullPath: '/app/risk-roadmap'
      preLoaderRoute: typeof AuthenticatedAppRiskRoadmapRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/risks': {
      id: '/_authenticated/app/risks'
      path: '/risks'
      fullPath: '/app/risks'
      preLoaderRoute: typeof AuthenticatedAppRisksRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/roadmap-analytics': {
      id: '/_authenticated/app/roadmap-analytics'
      path: '/roadmap-analytics'
      fullPath: '/app/roadmap-analytics'
      preLoaderRoute: typeof AuthenticatedAppRoadmapAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/roadmap-governance': {
      id: '/_authenticated/app/roadmap-governance'
      path: '/roadmap-governance'
      fullPath: '/app/roadmap-governance'
      preLoaderRoute: typeof AuthenticatedAppRoadmapGovernanceRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/scenarios': {
      id: '/_authenticated/app/scenarios'
      path: '/scenarios'
      fullPath: '/app/scenarios'
      preLoaderRoute: typeof AuthenticatedAppScenariosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/stage-gate-config': {
      id: '/_authenticated/app/stage-gate-config'
      path: '/stage-gate-config'
      fullPath: '/app/stage-gate-config'
      preLoaderRoute: typeof AuthenticatedAppStageGateConfigRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/stage-gates': {
      id: '/_authenticated/app/stage-gates'
      path: '/stage-gates'
      fullPath: '/app/stage-gates'
      preLoaderRoute: typeof AuthenticatedAppStageGatesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/stakeholders': {
      id: '/_authenticated/app/stakeholders'
      path: '/stakeholders'
      fullPath: '/app/stakeholders'
      preLoaderRoute: typeof AuthenticatedAppStakeholdersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/team': {
      id: '/_authenticated/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AuthenticatedAppTeamRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/timeline': {
      id: '/_authenticated/app/timeline'
      path: '/timeline'
      fullPath: '/app/timeline'
      preLoaderRoute: typeof AuthenticatedAppTimelineRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/work-items': {
      id: '/_authenticated/app/work-items'
      path: '/work-items'
      fullPath: '/app/work-items'
      preLoaderRoute: typeof AuthenticatedAppWorkItemsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/platform/branding': {
      id: '/_authenticated/platform/branding'
      path: '/branding'
      fullPath: '/platform/branding'
      preLoaderRoute: typeof AuthenticatedPlatformBrandingRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/expenses': {
      id: '/_authenticated/platform/expenses'
      path: '/expenses'
      fullPath: '/platform/expenses'
      preLoaderRoute: typeof AuthenticatedPlatformExpensesRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/finance': {
      id: '/_authenticated/platform/finance'
      path: '/finance'
      fullPath: '/platform/finance'
      preLoaderRoute: typeof AuthenticatedPlatformFinanceRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/invoice-template': {
      id: '/_authenticated/platform/invoice-template'
      path: '/invoice-template'
      fullPath: '/platform/invoice-template'
      preLoaderRoute: typeof AuthenticatedPlatformInvoiceTemplateRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/invoices': {
      id: '/_authenticated/platform/invoices'
      path: '/invoices'
      fullPath: '/platform/invoices'
      preLoaderRoute: typeof AuthenticatedPlatformInvoicesRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/landing': {
      id: '/_authenticated/platform/landing'
      path: '/landing'
      fullPath: '/platform/landing'
      preLoaderRoute: typeof AuthenticatedPlatformLandingRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/limits': {
      id: '/_authenticated/platform/limits'
      path: '/limits'
      fullPath: '/platform/limits'
      preLoaderRoute: typeof AuthenticatedPlatformLimitsRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/organizations': {
      id: '/_authenticated/platform/organizations'
      path: '/organizations'
      fullPath: '/platform/organizations'
      preLoaderRoute: typeof AuthenticatedPlatformOrganizationsRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/plans': {
      id: '/_authenticated/platform/plans'
      path: '/plans'
      fullPath: '/platform/plans'
      preLoaderRoute: typeof AuthenticatedPlatformPlansRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/project-purge': {
      id: '/_authenticated/platform/project-purge'
      path: '/project-purge'
      fullPath: '/platform/project-purge'
      preLoaderRoute: typeof AuthenticatedPlatformProjectPurgeRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/settings': {
      id: '/_authenticated/platform/settings'
      path: '/settings'
      fullPath: '/platform/settings'
      preLoaderRoute: typeof AuthenticatedPlatformSettingsRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/subscriptions': {
      id: '/_authenticated/platform/subscriptions'
      path: '/subscriptions'
      fullPath: '/platform/subscriptions'
      preLoaderRoute: typeof AuthenticatedPlatformSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/o/$slug/login': {
      id: '/o/$slug/login'
      path: '/o/$slug/login'
      fullPath: '/o/$slug/login'
      preLoaderRoute: typeof OSlugLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/invoice/$id': {
      id: '/_authenticated/app/invoice/$id'
      path: '/invoice/$id'
      fullPath: '/app/invoice/$id'
      preLoaderRoute: typeof AuthenticatedAppInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/projects/$id': {
      id: '/_authenticated/app/projects/$id'
      path: '/$id'
      fullPath: '/app/projects/$id'
      preLoaderRoute: typeof AuthenticatedAppProjectsIdRouteImport
      parentRoute: typeof AuthenticatedAppProjectsRoute
    }
    '/_authenticated/app/projects/new': {
      id: '/_authenticated/app/projects/new'
      path: '/new'
      fullPath: '/app/projects/new'
      preLoaderRoute: typeof AuthenticatedAppProjectsNewRouteImport
      parentRoute: typeof AuthenticatedAppProjectsRoute
    }
    '/_authenticated/platform/invoice/$id': {
      id: '/_authenticated/platform/invoice/$id'
      path: '/invoice/$id'
      fullPath: '/platform/invoice/$id'
      preLoaderRoute: typeof AuthenticatedPlatformInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/api/public/hooks/billing-run': {
      id: '/api/public/hooks/billing-run'
      path: '/api/public/hooks/billing-run'
      fullPath: '/api/public/hooks/billing-run'
      preLoaderRoute: typeof ApiPublicHooksBillingRunRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAppProjectsRouteChildren {
  AuthenticatedAppProjectsIdRoute: typeof AuthenticatedAppProjectsIdRoute
  AuthenticatedAppProjectsNewRoute: typeof AuthenticatedAppProjectsNewRoute
}

const AuthenticatedAppProjectsRouteChildren: AuthenticatedAppProjectsRouteChildren =
  {
    AuthenticatedAppProjectsIdRoute: AuthenticatedAppProjectsIdRoute,
    AuthenticatedAppProjectsNewRoute: AuthenticatedAppProjectsNewRoute,
  }

const AuthenticatedAppProjectsRouteWithChildren =
  AuthenticatedAppProjectsRoute._addFileChildren(
    AuthenticatedAppProjectsRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAboutRoute: typeof AuthenticatedAppAboutRoute
  AuthenticatedAppActionsRoute: typeof AuthenticatedAppActionsRoute
  AuthenticatedAppAgileRoute: typeof AuthenticatedAppAgileRoute
  AuthenticatedAppAiAssistRoute: typeof AuthenticatedAppAiAssistRoute
  AuthenticatedAppAuditLogRoute: typeof AuthenticatedAppAuditLogRoute
  AuthenticatedAppBenefitsRoute: typeof AuthenticatedAppBenefitsRoute
  AuthenticatedAppBillingRoute: typeof AuthenticatedAppBillingRoute
  AuthenticatedAppBusinessUnitsRoute: typeof AuthenticatedAppBusinessUnitsRoute
  AuthenticatedAppChartThemeRoute: typeof AuthenticatedAppChartThemeRoute
  AuthenticatedAppConfigurationRoute: typeof AuthenticatedAppConfigurationRoute
  AuthenticatedAppCostVsBenefitRoute: typeof AuthenticatedAppCostVsBenefitRoute
  AuthenticatedAppDataEditorRoute: typeof AuthenticatedAppDataEditorRoute
  AuthenticatedAppDecisionsRoute: typeof AuthenticatedAppDecisionsRoute
  AuthenticatedAppDemandPipelineRoute: typeof AuthenticatedAppDemandPipelineRoute
  AuthenticatedAppDependenciesRoute: typeof AuthenticatedAppDependenciesRoute
  AuthenticatedAppExecutiveRoute: typeof AuthenticatedAppExecutiveRoute
  AuthenticatedAppExecutiveCockpitRoute: typeof AuthenticatedAppExecutiveCockpitRoute
  AuthenticatedAppExecutiveReportsRoute: typeof AuthenticatedAppExecutiveReportsRoute
  AuthenticatedAppFinancialsRoute: typeof AuthenticatedAppFinancialsRoute
  AuthenticatedAppFyAllocationRoute: typeof AuthenticatedAppFyAllocationRoute
  AuthenticatedAppGovernanceChannelsRoute: typeof AuthenticatedAppGovernanceChannelsRoute
  AuthenticatedAppIssuesRoute: typeof AuthenticatedAppIssuesRoute
  AuthenticatedAppLatestUpdatesRoute: typeof AuthenticatedAppLatestUpdatesRoute
  AuthenticatedAppLessonsRoute: typeof AuthenticatedAppLessonsRoute
  AuthenticatedAppMyWorkRoute: typeof AuthenticatedAppMyWorkRoute
  AuthenticatedAppNavigationRoute: typeof AuthenticatedAppNavigationRoute
  AuthenticatedAppPermissionsRoute: typeof AuthenticatedAppPermissionsRoute
  AuthenticatedAppPhaseFinancialsRoute: typeof AuthenticatedAppPhaseFinancialsRoute
  AuthenticatedAppPortfolioMovementsRoute: typeof AuthenticatedAppPortfolioMovementsRoute
  AuthenticatedAppPortfolioSegmentationRoute: typeof AuthenticatedAppPortfolioSegmentationRoute
  AuthenticatedAppPrioritisationRoute: typeof AuthenticatedAppPrioritisationRoute
  AuthenticatedAppProgramsRoute: typeof AuthenticatedAppProgramsRoute
  AuthenticatedAppProjectAccessRoute: typeof AuthenticatedAppProjectAccessRoute
  AuthenticatedAppProjectInfographicRoute: typeof AuthenticatedAppProjectInfographicRoute
  AuthenticatedAppProjectPurgeRoute: typeof AuthenticatedAppProjectPurgeRoute
  AuthenticatedAppProjectsRoute: typeof AuthenticatedAppProjectsRouteWithChildren
  AuthenticatedAppReleaseRegisterRoute: typeof AuthenticatedAppReleaseRegisterRoute
  AuthenticatedAppResourcesRoute: typeof AuthenticatedAppResourcesRoute
  AuthenticatedAppRiskRoadmapRoute: typeof AuthenticatedAppRiskRoadmapRoute
  AuthenticatedAppRisksRoute: typeof AuthenticatedAppRisksRoute
  AuthenticatedAppRoadmapAnalyticsRoute: typeof AuthenticatedAppRoadmapAnalyticsRoute
  AuthenticatedAppRoadmapGovernanceRoute: typeof AuthenticatedAppRoadmapGovernanceRoute
  AuthenticatedAppScenariosRoute: typeof AuthenticatedAppScenariosRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppStageGateConfigRoute: typeof AuthenticatedAppStageGateConfigRoute
  AuthenticatedAppStageGatesRoute: typeof AuthenticatedAppStageGatesRoute
  AuthenticatedAppStakeholdersRoute: typeof AuthenticatedAppStakeholdersRoute
  AuthenticatedAppTeamRoute: typeof AuthenticatedAppTeamRoute
  AuthenticatedAppTimelineRoute: typeof AuthenticatedAppTimelineRoute
  AuthenticatedAppWorkItemsRoute: typeof AuthenticatedAppWorkItemsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppInvoiceIdRoute: typeof AuthenticatedAppInvoiceIdRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAboutRoute: AuthenticatedAppAboutRoute,
  AuthenticatedAppActionsRoute: AuthenticatedAppActionsRoute,
  AuthenticatedAppAgileRoute: AuthenticatedAppAgileRoute,
  AuthenticatedAppAiAssistRoute: AuthenticatedAppAiAssistRoute,
  AuthenticatedAppAuditLogRoute: AuthenticatedAppAuditLogRoute,
  AuthenticatedAppBenefitsRoute: AuthenticatedAppBenefitsRoute,
  AuthenticatedAppBillingRoute: AuthenticatedAppBillingRoute,
  AuthenticatedAppBusinessUnitsRoute: AuthenticatedAppBusinessUnitsRoute,
  AuthenticatedAppChartThemeRoute: AuthenticatedAppChartThemeRoute,
  AuthenticatedAppConfigurationRoute: AuthenticatedAppConfigurationRoute,
  AuthenticatedAppCostVsBenefitRoute: AuthenticatedAppCostVsBenefitRoute,
  AuthenticatedAppDataEditorRoute: AuthenticatedAppDataEditorRoute,
  AuthenticatedAppDecisionsRoute: AuthenticatedAppDecisionsRoute,
  AuthenticatedAppDemandPipelineRoute: AuthenticatedAppDemandPipelineRoute,
  AuthenticatedAppDependenciesRoute: AuthenticatedAppDependenciesRoute,
  AuthenticatedAppExecutiveRoute: AuthenticatedAppExecutiveRoute,
  AuthenticatedAppExecutiveCockpitRoute: AuthenticatedAppExecutiveCockpitRoute,
  AuthenticatedAppExecutiveReportsRoute: AuthenticatedAppExecutiveReportsRoute,
  AuthenticatedAppFinancialsRoute: AuthenticatedAppFinancialsRoute,
  AuthenticatedAppFyAllocationRoute: AuthenticatedAppFyAllocationRoute,
  AuthenticatedAppGovernanceChannelsRoute:
    AuthenticatedAppGovernanceChannelsRoute,
  AuthenticatedAppIssuesRoute: AuthenticatedAppIssuesRoute,
  AuthenticatedAppLatestUpdatesRoute: AuthenticatedAppLatestUpdatesRoute,
  AuthenticatedAppLessonsRoute: AuthenticatedAppLessonsRoute,
  AuthenticatedAppMyWorkRoute: AuthenticatedAppMyWorkRoute,
  AuthenticatedAppNavigationRoute: AuthenticatedAppNavigationRoute,
  AuthenticatedAppPermissionsRoute: AuthenticatedAppPermissionsRoute,
  AuthenticatedAppPhaseFinancialsRoute: AuthenticatedAppPhaseFinancialsRoute,
  AuthenticatedAppPortfolioMovementsRoute:
    AuthenticatedAppPortfolioMovementsRoute,
  AuthenticatedAppPortfolioSegmentationRoute:
    AuthenticatedAppPortfolioSegmentationRoute,
  AuthenticatedAppPrioritisationRoute: AuthenticatedAppPrioritisationRoute,
  AuthenticatedAppProgramsRoute: AuthenticatedAppProgramsRoute,
  AuthenticatedAppProjectAccessRoute: AuthenticatedAppProjectAccessRoute,
  AuthenticatedAppProjectInfographicRoute:
    AuthenticatedAppProjectInfographicRoute,
  AuthenticatedAppProjectPurgeRoute: AuthenticatedAppProjectPurgeRoute,
  AuthenticatedAppProjectsRoute: AuthenticatedAppProjectsRouteWithChildren,
  AuthenticatedAppReleaseRegisterRoute: AuthenticatedAppReleaseRegisterRoute,
  AuthenticatedAppResourcesRoute: AuthenticatedAppResourcesRoute,
  AuthenticatedAppRiskRoadmapRoute: AuthenticatedAppRiskRoadmapRoute,
  AuthenticatedAppRisksRoute: AuthenticatedAppRisksRoute,
  AuthenticatedAppRoadmapAnalyticsRoute: AuthenticatedAppRoadmapAnalyticsRoute,
  AuthenticatedAppRoadmapGovernanceRoute:
    AuthenticatedAppRoadmapGovernanceRoute,
  AuthenticatedAppScenariosRoute: AuthenticatedAppScenariosRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppStageGateConfigRoute: AuthenticatedAppStageGateConfigRoute,
  AuthenticatedAppStageGatesRoute: AuthenticatedAppStageGatesRoute,
  AuthenticatedAppStakeholdersRoute: AuthenticatedAppStakeholdersRoute,
  AuthenticatedAppTeamRoute: AuthenticatedAppTeamRoute,
  AuthenticatedAppTimelineRoute: AuthenticatedAppTimelineRoute,
  AuthenticatedAppWorkItemsRoute: AuthenticatedAppWorkItemsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppInvoiceIdRoute: AuthenticatedAppInvoiceIdRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedPlatformRouteChildren {
  AuthenticatedPlatformBrandingRoute: typeof AuthenticatedPlatformBrandingRoute
  AuthenticatedPlatformExpensesRoute: typeof AuthenticatedPlatformExpensesRoute
  AuthenticatedPlatformFinanceRoute: typeof AuthenticatedPlatformFinanceRoute
  AuthenticatedPlatformInvoiceTemplateRoute: typeof AuthenticatedPlatformInvoiceTemplateRoute
  AuthenticatedPlatformInvoicesRoute: typeof AuthenticatedPlatformInvoicesRoute
  AuthenticatedPlatformLandingRoute: typeof AuthenticatedPlatformLandingRoute
  AuthenticatedPlatformLimitsRoute: typeof AuthenticatedPlatformLimitsRoute
  AuthenticatedPlatformOrganizationsRoute: typeof AuthenticatedPlatformOrganizationsRoute
  AuthenticatedPlatformPlansRoute: typeof AuthenticatedPlatformPlansRoute
  AuthenticatedPlatformProjectPurgeRoute: typeof AuthenticatedPlatformProjectPurgeRoute
  AuthenticatedPlatformSettingsRoute: typeof AuthenticatedPlatformSettingsRoute
  AuthenticatedPlatformSubscriptionsRoute: typeof AuthenticatedPlatformSubscriptionsRoute
  AuthenticatedPlatformInvoiceIdRoute: typeof AuthenticatedPlatformInvoiceIdRoute
}

const AuthenticatedPlatformRouteChildren: AuthenticatedPlatformRouteChildren = {
  AuthenticatedPlatformBrandingRoute: AuthenticatedPlatformBrandingRoute,
  AuthenticatedPlatformExpensesRoute: AuthenticatedPlatformExpensesRoute,
  AuthenticatedPlatformFinanceRoute: AuthenticatedPlatformFinanceRoute,
  AuthenticatedPlatformInvoiceTemplateRoute:
    AuthenticatedPlatformInvoiceTemplateRoute,
  AuthenticatedPlatformInvoicesRoute: AuthenticatedPlatformInvoicesRoute,
  AuthenticatedPlatformLandingRoute: AuthenticatedPlatformLandingRoute,
  AuthenticatedPlatformLimitsRoute: AuthenticatedPlatformLimitsRoute,
  AuthenticatedPlatformOrganizationsRoute:
    AuthenticatedPlatformOrganizationsRoute,
  AuthenticatedPlatformPlansRoute: AuthenticatedPlatformPlansRoute,
  AuthenticatedPlatformProjectPurgeRoute:
    AuthenticatedPlatformProjectPurgeRoute,
  AuthenticatedPlatformSettingsRoute: AuthenticatedPlatformSettingsRoute,
  AuthenticatedPlatformSubscriptionsRoute:
    AuthenticatedPlatformSubscriptionsRoute,
  AuthenticatedPlatformInvoiceIdRoute: AuthenticatedPlatformInvoiceIdRoute,
}

const AuthenticatedPlatformRouteWithChildren =
  AuthenticatedPlatformRoute._addFileChildren(
    AuthenticatedPlatformRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPlatformRoute: typeof AuthenticatedPlatformRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPlatformRoute: AuthenticatedPlatformRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForcePasswordChangeRoute: ForcePasswordChangeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  OSlugLoginRoute: OSlugLoginRoute,
  ApiPublicHooksBillingRunRoute: ApiPublicHooksBillingRunRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
